spring:
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring_boot_template?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
server:
  port: 8080

# 自定义的jwt配置
jwt:
  # 过期时间：2小时
  expire: 7200000
  # 密钥
  secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52
